name: Validate SSIS Packages

on:
  push:

jobs:
  validate:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Ensure Dependencies for SSIS
        run: |
          Write-Host "Checking for SSIS Runtime..."

      - name: Validate SSIS Packages
        shell: pwsh # Use PowerShell Core
        run: |
          pwsh -File "./NewScript.ps1" -projectDirectory "./Integration Services Project3"

