name: Validate SSIS Packages

on:
  push:

jobs:
  validate:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run PowerShell Script
        run: pwsh -File "C:\Users\harshit.k.sevkani\script.ps1"
