name: Validate SSIS Packages

on:
  push:

jobs:
  validate-ssis:
    runs-on: self-hosted  # Uses your self-hosted runner

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Verify .NET Framework
      - name: Verify .NET Framework
        run: |
          powershell -Command "
            Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -Recurse |
            Get-ItemProperty -Name Version -ErrorAction SilentlyContinue |
            Where-Object { $_.Version -match '^\d+\.\d+' } |
            Select-Object PSChildName, Version
          "

      # Step 3: Verify SSIS runtime dependency
      - name: Verify SSIS Runtime DLL
        run: |
          if (!(Test-Path -Path "$env:USERPROFILE\lib\Microsoft.SQLServer.ManagedDTS.dll")) {
              Write-Error 'SSIS Runtime DLL is missing. Ensure SSIS runtime is installed.'
          } else {
              Write-Host 'SSIS Runtime DLL is present.'
          }

      # Step 4: Run the PowerShell script
      - name: Run Validation Script
        shell: powershell
        run: |
          "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -File "./NewScript.ps1" -projectDirectory "./Integration Services Project3"

      # Step 5: Log Success
      - name: Log Success
        run: echo "SSIS Package Validation Completed Successfully."
