name: Validate SSIS Packages

on:
  push: # Trigger the workflow on push events

jobs:
  validate:
    runs-on: self-hosted # Use your self-hosted runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Ensure Dependencies for SSIS
        run: |
          # Verify .NET Framework and SSIS runtime are installed
          Write-Host "Checking for SSIS Runtime..."

      - name: Validate SSIS Packages
        shell: pwsh
        run: |
          # Execute the PowerShell script
          pwsh -File "./NewScript.ps1" -projectDirectory "./Integration Services Project3"
